- hosts: webservers
  vars:
    root_dir: /data/nginx/html

  tasks:
    - name: Mount up device
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
      become: yes

    - name: create filesystem
      filesystem:
        fstype: xfs
        dev: /dev/sdb1
      become: yes

    - name: Mount up device by label
      mount:
        path: /data
        src: /dev/sdb1
        fstype: xfs
        state: mounted
      become: yes

    - name: create directory for nginx files
      file:
        path: "{{ root_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root
      become: yes

    - name: update nginx config
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: nginx
      notify:
        - reload nginx
      become: yes

    - name: update nginx statics
      copy:
        src: "files/"
        dest: "{{ root_dir }}"
        owner: nginx
      notify:
        - reload nginx
      become: yes

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
        daemon_reload: yes
        enabled: yes
      become: yes
