---
hosts:
  - hostname: test1
    role: worker
    cpus: 2
    memory: 4096
    ip: 10.1.1.101
    port: 10101
    box: bento/centos-7.9

  - hostname: test2
    role: worker
    cpus: 2
    memory: 4096
    ip: 10.1.1.102
    port: 10102
    box: bento/centos-7.9

  - hostname: test3
    role: worker
    cpus: 2
    memory: 4096
    ip: 10.1.1.103
    port: 10103
    box: bento/centos-7.9

  - hostname: test4
    role: worker
    cpus: 2
    memory: 4096
    ip: 10.1.1.104
    port: 10104
    box: bento/centos-7.9
