- hosts: appservers
  tasks:
    - name: update docker config
      copy:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
      notify:
        - reload docker
      become: yes

  handlers:
    - name: reload docker
      service:
        name: docker
        state: reloaded
      become: yes
